{% set name = "pytest-click" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_click-{{ version }}.tar.gz
  sha256: fdd9f6721f877dda021e7c5dc73e70aecd37e5ed23ec6820f8a7b3fd7b4f8d30

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.6.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - click >=6.0
    - pytest >=5.0

test:
  imports:
    - pytest_click
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Stranger6667/pytest-click
  summary: Pytest plugin for Click
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
